feat: Stores from across Europe
openfoodfacts/robotoff pull request #1175
Opened 2023-08-18 08:31 UTC by teolemon

### What
- feat: Stores from across Europe

2023-08-20 17:47 UTC, raphael0202 requested changes

2023-08-20 18:26 UTC, teolemon commented on data/ocr/store_regex.txt
> +Penny
Supprimons dans le doute. Mais penny est un vieux mot, et même au UK, je ne pense pas qu'on l'ait des masse. Les magasins a 10 francs sont les pound store

2023-08-21 06:05 UTC, teolemon commented on data/ocr/store_regex.txt
> +Penny
```suggestion
```

2023-08-21 07:53 UTC, raphael0202 approved these changes

2023-08-21 07:53 UTC, merged