feat: Added Polish brands, stores and labels
openfoodfacts/robotoff pull request #1184
Opened 2023-08-28 09:18 UTC by ArturLange

### What
- I added regexes to stores and brands popular in Poland and links to popular Polish labels

2023-08-28 12:02 UTC, raphael0202 requested changes

2023-08-28 12:02 UTC, raphael0202 commented on data/ocr/label_flashtext.txt
> +en:vegan||suitable for vegans
As vegan is already there you can just add "vegans" as a pattern.

2023-08-28 12:02 UTC, raphael0202 commented on data/ocr/store_regex.txt
> +Action
Hum it will introduce many false positive, it's quite a common word.

2023-08-28 12:02 UTC, raphael0202 commented on data/ocr/store_regex.txt
> +Aldi||biscotto
Same thing about false positive maybe.

2023-08-30 10:35 UTC, ArturLange commented on data/ocr/brand_logo_annotation.txt
> +TYMBARK||Tymbark
You're right, that wasn't obvious to me, I thought it's supposed to be the way it's written on the packaging.
In that case I shouldn't add those without knowledge about Google Cloud Vision, is that right?

2023-08-30 12:04 UTC, teolemon commented on data/ocr/store_regex.txt
> +Aldi||biscotto
```suggestion
```

2023-08-30 12:04 UTC, teolemon commented on data/ocr/store_regex.txt
> +Action
```suggestion
```

2023-08-31 08:58 UTC, raphael0202 commented on data/ocr/brand_logo_annotation.txt
> +TYMBARK||Tymbark
```suggestion
```

2023-08-31 08:59 UTC, raphael0202 commented on data/ocr/label_flashtext.txt
> +en:vegan||suitable for vegans
```suggestion
en:vegan||vegans
```

2023-08-31 15:38 UTC, ArturLange commented
@raphael0202 I removed **Netto** from `store_regex.txt` after your comments - it's also a common word on packaging.
Is it ok if I just leave the various own brands of **Netto**? 
```
Netto||bergio
Netto||corsarro
Netto||happy vege
Netto||miletto
Netto||paradiso
Netto||quallio
Netto||rajski sad
Netto||sztuka mięsa
Netto||toremo
```

2023-09-04 08:39 UTC, raphael0202 commented
Stores are applied automatically, that's the issue... I'm not super fan of this store system we put in place, I would much rather deduce the store from the brand in Robotoff (see https://github.com/openfoodfacts/robotoff/discussions/1225).
If you don't mind I would much rather not include additional stores in this file, as it takes time to clean the DB once false positive are introduced).

2025-07-08 17:20 UTC, JagjeevanAK commented
@ArturLange any  update on this PR ?

2025-08-20 11:33 UTC, teolemon commented on data/ocr/store_regex.txt
> +Netto||paradiso
```suggestion
```

2025-08-21 10:26 UTC, raphael0202 commented
As we don't want to rely anymore on manual detection to detect store/brands (due to risks of false positive), I'm closing this PR.

2025-08-21 10:26 UTC, closed without merging