more-category-preprocessing
openfoodfacts/robotoff pull request #309
Opened 2021-01-18 19:14 UTC by teolemon

2021-01-19 13:51 UTC, alex-marty requested changes

2021-01-19 13:51 UTC, alex-marty commented on robotoff/elasticsearch/category/preprocessing.py
> +    "fr": re.compile(r"délicieux"),
Error on this line: the key "fr" is specified twice. Combine in the first regex:

```suggestion
    "fr": re.compile(r"gourmand|délicieux"),
```

2021-01-20 08:15 UTC, alex-marty approved these changes

2021-08-24 16:53 UTC, kulizhsy approved these changes

2021-08-25 07:41 UTC, merged