Adding MongoDB container to Robotoff
openfoodfacts/robotoff pull request #693
Opened 2022-04-09 12:52 UTC by Jagrutiti

### What
I have tried to add the MongoDB container to docker.
When I run `docker-compose up` it works fine. No error is thrown. So I think it works fine.
![Screenshot from 2022-04-09 18-11-04](https://user-images.githubusercontent.com/28809492/162574566-6b2775da-34b4-498b-877a-ca62003951a2.png)

But when I call `save_annotation` function through pdb it throws the following error. 
![Screenshot from 2022-04-09 18-18-14](https://user-images.githubusercontent.com/28809492/162574754-7b60c708-d987-40e5-af4f-4c89f4889a3e.png)

### Closes
- #692
### Part of 
- I was actually trying to work on https://github.com/openfoodfacts/robotoff/issues/606 when I encountered this error.

2022-04-11 07:55 UTC, alexgarel requested changes
You don't need the mongodb.yml file

2022-04-16 17:42 UTC, Jagrutiti commented
Hey @alexgarel 

I am just not sure how to provide a demo database to the user to download and extract?

2022-09-26 15:22 UTC, raphael0202 commented on docker/dev.yml
> +    # Note: keep it as close a possible to mongodb.yml
This line should be removed I think

2022-09-26 15:23 UTC, raphael0202 commented on doc/how-to-guides/deployment/dev-install.md
> +    The MongoDB configuration is now compelete.
compelete -> complete

2022-09-26 16:17 UTC, raphael0202 approved these changes

2022-09-27 09:16 UTC, merged