feat: Filter product by country to get answered questions
openfoodfacts/robotoff pull request #905
Opened 2022-09-20 14:46 UTC by Jagrutiti

### What
- Added `country `parameter to the `UnansweredQuestionCollection` API.

### Closes
- #901

2022-09-21 10:10 UTC, alexgarel commented on robotoff/app/api.py
>              "keep_types": [question_type],
Replace this by:
```suggestion
            "keep_types": [question_type] if question_type else None,
```

2022-09-21 10:11 UTC, alexgarel commented on robotoff/app/api.py
>              "keep_types": [question_type],
That said, I don't think using this API without question_type as any sense, so I would better make question_type mandatory.

2022-09-22 07:18 UTC, raphael0202 requested changes

2022-09-22 07:18 UTC, raphael0202 commented on robotoff/app/api.py
> +
Can you remove this debugging code?

2022-09-22 07:18 UTC, raphael0202 commented on robotoff/app/core.py
> +
Same comment as above about debugging

2022-09-22 07:18 UTC, raphael0202 commented on tests/integration/test_api.py
> +    d = ProductInsightFactory(
You don't have to assign the product to `d` variable as you're not using it (local variable 'd' is assigned to but never used)

2022-09-23 10:31 UTC, alexgarel commented on tests/integration/test_core_integration.py
> +    assert insight_data_items6[0]["countries"] == "en:india"
you should also test you have only 1 product

```suggestion
    assert len(insight_data_items6) == 1
```

2022-09-23 10:33 UTC, alexgarel approved these changes
We need just a small improvement on tests.

I validate the PR but please, apply suggestions before merging, if you agree.

2022-09-23 10:33 UTC, alexgarel commented on tests/integration/test_api.py
> +    )
Adding only one product, you don't really test the filter is effective.

To test that you should add another product in another country
```suggestion
    ProductInsightFactory(
        type="location", value_tag="en:dates", barcode="033", countries=["en:france"]
    )
```

2022-09-27 08:36 UTC, merged